baseURL = 'https://promo.yiwuyimei.com/'
languageCode = 'en-US'
title = 'Yiwuyimei Product Showcase'
theme = 'yiwuyimei'

[params]
  description = 'Yiwuyimei Product Showcase Website'
  author = 'yiwuyimei'

[taxonomies]
  category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  
  [[menu.main]]
    identifier = 'products'
    name = 'Products'
    url = '/products/'
    weight = 2
  
  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 3
